spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

oidc:
  kakao:
    jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
    issuer: https://kauth.kakao.com
    audience: ${KAKAO_NATIVE_APP_KEY:}
  apple:
    jwk-set-uri: https://appleid.apple.com/auth/keys
    issuer: https://appleid.apple.com
    audience: ${APPLE_SERVICE_ID:}

spring-doc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    tags-sorter: alpha
    operations-sorter : method
    path: /swagger-ui
    doc-expansion : none
