management:
  endpoints:
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: health
      base-path: /cherrypic-actuator
    access:
      default: none
  endpoint:
    health:
      access: unrestricted