spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

oidc:
  kakao:
    jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
    issuer: https://kauth.kakao.com
    audience: ${KAKAO_NATIVE_APP_KEY:}
  apple:
    jwk-set-uri: https://appleid.apple.com/auth/keys
    issuer: https://appleid.apple.com
    audience: ${APPLE_SERVICE_ID:}

jwt:
  access-token-secret: ${JWT_ACCESS_TOKEN_SECRET}
  refresh-token-secret: ${JWT_REFRESH_TOKEN_SECRET}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME:7200}
  refresh-token-expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME:172800}
  issuer: ${JWT_ISSUER}

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  s3:
    bucket: ${S3_BUCKET}
    endpoint: ${S3_ENDPOINT:https://s3.ap-northeast-2.amazonaws.com}

iamport:
  key: ${IAMPORT_KEY}
  secret: ${IAMPORT_SECRET}

spring-doc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    tags-sorter: alpha
    operations-sorter : method
    path: /swagger-ui
    doc-expansion : none

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
