management:
  endpoints:
    jmx:
      exposure:
        exclude: "*"
    web:
      exposure:
        include: health
      base-path: /cherrypic-actuator
    access:
      default: none
  endpoint:
    health:
      access: unrestricted

spring-doc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    tags-sorter: alpha
    operations-sorter : method
    path: /swagger-ui
    doc-expansion : none
